version: "3.9"
services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    restart: unless-stopped
    network_mode: host
